scientific_name = [
    "Agriotes spp.",
    "Anthonomus grandis",
    "Miridae",
    "Pectinophora gossypiella",
    "Spodoptera littoralis",
    "Tetranychus urticae",
    "Thrips tabaci",
    "Aphididae",
    "Bemisia tabaci",
    "Earias insulana",
    "Helicoverpa armigera",
    "Chrysopidae",
    "Coccinelidae",
    "Nabidae",
    "Anthonomus grandis (larva)",
    "Pectinophora gossypiella (larva)",
    "Spodoptera littoralis (larva)",
    "Earias insulana (larva)",
    "Helicoverpa armigera (larva)"
]

descriptions = [
    "Agriotes spp.: Slender brown beetle with long antennae and a click mechanism.",
    "Anthonomus grandis: Small gray-brown weevil with a long curved snout and bent antennae.",
    "Miridae: Small soft-bodied bug with variable color and a cuneus on wings.",
    "Pectinophora gossypiella: Small moth with gray wings and pink tint, held tent-like at rest.",
    "Spodoptera littoralis: Brown moth with white hindwings and dark border; forewings mottled.",
    "Tetranychus urticae: Tiny red or yellow mite with two dark spots; white webbing present.",
    "Thrips tabaci: Pale yellow insect with narrow fringed wings; fast-moving on leaves.",
    "Aphididae: Soft, pear-shaped body with cornicles; winged or wingless forms.",
    "Bemisia tabaci: Tiny insect with white waxy wings; yellow body partly exposed.",
    "Earias insulana: Small green moth with narrow wings; fades to yellow when aged.",
    "Helicoverpa armigera: Light brown moth with mottled wings and pale hindwings; medium size.",
    "Chrysopidae: Slender green insect with large clear wings and golden metallic eyes.",
    "Coccinelidae: Rounded beetle with spotted red or yellow elytra; dome-shaped body.",
    "Nabidae: Slender brown bug with long legs, narrow head, and visible wing veins.",
    "Anthonomus grandis (larva): White, legless C-shaped larva with brown head; hidden in cotton buds.",
    "Pectinophora gossypiella (larva): Pink caterpillar with smooth body and brown head; bores into bolls.",
    "Spodoptera littoralis (larva): Caterpillar with pale stripes and black spots; body color varies.",
    "Earias insulana (larva): Caterpillar with pale dorsal lines, fine spines; green to pink body.",
    "Helicoverpa armigera (larva): Smooth striped caterpillar with black side spots; color varies."
]

opt_descriptions = [
    "Agriotes spp.: Brown elongate beetle with grooved elytra and long antennae.",
    "Anthonomus grandis: Gray-brown weevil with curved snout, compact form, clubbed antennae.",
    "Miridae: Oval soft-bodied bug, patterned wings, distinct cuneus, variable colors.",
    "Pectinophora gossypiella: Gray-pink moth with narrow fringed wings and resting tent posture.",
    "Spodoptera littoralis: Mottled forewings with wavy bands, pale hindwings with dark border.",
    "Tetranychus urticae: Oval mite with red or yellow body, two dark dorsal spots, eight legs.",
    "Thrips tabaci: Slender insect with fringed narrow wings, segmented antennae, yellowish body.",
    "Aphididae: Pear-shaped soft insect with visible cornicles and varied body colors.",
    "Bemisia tabaci: White waxy wings over yellow body, wings held apart in a tent-like posture.",
    "Earias insulana: Green moth with long pointed wings, fading yellow over time, soft scales.",
    "Helicoverpa armigera: Light brown moth with speckled forewings and distinct reniform spot.",
    "Chrysopidae: Green lacewing with large golden eyes and transparent net-veined wings.",
    "Coccinelidae: Dome-shaped beetle with convex elytra, bright colors, and black spots.",
    "Nabidae: Slender predatory bug with narrow head, long legs, and veined hemelytra.",
    "Anthonomus grandis (larva): White C-shaped grub with smooth body, brown head, no legs.",
    "Pectinophora gossypiella (larva): Pinkish smooth caterpillar with brown head and faint body segmentation.",
    "Spodoptera littoralis (larva): Striped larva with dark dorsal spots, fine hairs, and varied coloration.",
    "Earias insulana (larva): Caterpillar with pale dorsal lines, fine spines; green to pink body.",
    "Helicoverpa armigera (larva): Smooth caterpillar with longitudinal stripes and black lateral tubercles."
]

descripciones = [
    "Agriotes spp.: Brown elongate body, grooved elytra, long filiform antennae.",
    "Anthonomus grandis: Gray-brown compact body, curved rostrum, clubbed antennae.",
    "Miridae: Variable-colored soft body, hemelytra with visible cuneus, smooth cuticle.",
    "Pectinophora gossypiella: Pale gray-pink body, narrow fringed wings, tented at rest.",
    "Spodoptera littoralis: Brown forewings with wavy bands, pale hindwings with dark margin.",
    "Tetranychus urticae: Yellow to red oval body, two dark dorsal spots, eight slender legs.",
    "Thrips tabaci: Pale yellow slender body, narrow fringed wings, segmented antennae.",
    "Aphididae: Green to black soft body, pear-shaped abdomen, cornicles on posterior end.",
    "Bemisia tabaci: White waxy wings, yellowish thorax visible, wings angled tent-like.",
    "Earias insulana: Green slender moth body, pointed forewings, fades yellow with age.",
    "Helicoverpa armigera: Light brown moth body, mottled forewings, kidney-shaped reniform spot.",
    "Chrysopidae: Bright green body, transparent net-veined wings, metallic golden compound eyes.",
    "Coccinelidae: Red or yellow dome-shaped body, black elytral spots, convex profile.",
    "Nabidae: Slender brown body, narrow pronotum, long legs, clear wing venation.",
    "Anthonomus grandis (larva): White legless C-shaped body, smooth texture, brown sclerotized head.",
    "Pectinophora gossypiella (larva): Pink smooth larva, segmented cuticle, small brown head capsule.",
    "Spodoptera littoralis (larva): Striped body with dark dorsal spots, fine setae, pale lateral lines.",
    "Earias insulana (larva): Green to pink caterpillar, pale longitudinal lines, short black setae.",
    "Helicoverpa armigera (larva): Green to brown cylindrical body, dark lateral tubercles, striped dorsum."
]